version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 9mREsvXDs9Gk89Ef
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data